### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by melih-unsal** [griffbr/ODMD#1]
Hi, do you plan to share a pre-trained model?

**Comment by griffbr** [comment]
Hello melih1996,

Thank you for your question! I've added our pretrained, full-motion DBox model here: [/results/model/DBox_pretrained/DBox_pretrained_paper.pt.](https://github.com/griffbr/ODMD/tree/main/results/model/DBox_pretrained) To test this model, all you have to do is uncomment line 12 here: [/demo/demo_DBox_eval.py](https://github.com/griffbr/ODMD/blob/main/demo/demo_DBox_eval.py).

Thanks again!
Brent
