### ISSUE TITLE
how to test on phone

### ISSUE THREAD

**Issue by jinde-liu** [griffbr/ODMD#10]
Hello Brent,
I figured out how to run the model overall, and I know how to feed data into the model, but when the camera comes from a phone, how do I get the motion information from the phone. 

Best wishes,
Kidd

**Comment by griffbr** [comment]
Hey Kidd,

Thanks for your question and interest in ODMD.

For the ODMD phone results in our [paper](https://openaccess.thecvf.com/content/CVPR2021/html/Griffin_Depth_From_Camera_Motion_and_Object_Detection_CVPR_2021_paper.html), "we take sets of ten pictures with target objects in view, and we estimate the camera movement between images using markings on the ground (e.g., sections of sidewalk)" (Section 4.1). Basically, we manually measured ground truth object depth and camera movement distances to provide a phone-based benchmark and results with this work.

On the other hand, if you find a more automated way to estimate phone motion, please share details in this thread!

Best,
Brent
