### ISSUE TITLE
test

### ISSUE THREAD

**Issue by Halfpoint1** [griffbr/ODMD#2]
How to test mp4 or avi files？

**Comment by griffbr** [comment]
Hello Halfpoint1,

Thank you for your question! To use video with ODMD, I would convert the video to a sequence of images (here is a [quick tutorial](https://medium.com/@iKhushPatel/convert-video-to-images-images-to-video-using-opencv-python-db27a128a481) I found for that process) and then process each image using your chosen object detector. This will generate a sequence of bounding boxes that can be used with any ODMD-trained network.

Best,
Brent
