### ISSUE TITLE
Training DBox on driving

### ISSUE THREAD

**Issue by Liuuuu54** [griffbr/ODMD#3]
Greeting!
I interested in using DBox on the driving dataset, But the default model config seems like indoor(z_lim:[0.55,1]).
I'd appreciate it if you release the training config about driving or camera phone on paper examples.

**Comment by griffbr** [comment]
Greetings Liuuuu54,

Thanks for your comment. This is actually the same z_lim that we use for driving and camera phone experiments in our [paper](https://arxiv.org/abs/2103.01468). One benefit of our approach is that we use a dimensionless input-loss formulation (see Equation 14), so DBox can predict object depth across domains with vastly different image resolutions and camera movement ranges. With that said, the random movement profile and camera parameters we used for ODMS / camera phone experiments are slightly different (see configuration discussion on DBox_z at the very end of Section 3.3). If you want to use the ODMS configuration, just change lines 14-15 in [/demo/demo_DBox_train.py](https://github.com/griffbr/ODMD/blob/main/demo/demo_DBox_train.py) to:

datagen_config = "../config/data_gen/ODMS.yaml"
camera_config = "../config/camera/ODMS_camera.yaml"

Best,
Brent
