### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by Frank-Michel** [griffbr/ODMD#4]
Hi Brent,

This is a very interesting publication and it is nice that you are making the code publicly available so early.

I have a question about the input data format in case one would like to run their own images with their own bounding box detections and camera poses. Looking at all the datasets provided in the repository I saw that the bounding box detections are all saved in the normalized format (xc_norm, yc_norm, w_norm, h_norm, Z) and I am not sure how to arrive at the normalized bounding box positions without a depth estimate or the bounding box width and height in 3D. Could you please provide more details on how to create input data for your method, also for the normalized camera poses.

Example input data could be as follows:
Image size (640 480)
camera pose 0 
[[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]]
bounding box 0 
[320, 240, 100, 80]

camera pose 1 
[[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.2, 1.0]]
bounding box 1 
[320, 240, 120, 115]

camera pose 2
[[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.5, 1.0]]
bounding box 2
[320, 240, 150, 135]

Thanks.

**Comment by griffbr** [comment]
Hi Frank-Mic,

Thank you for your interest in this work and for your question.

Bounding boxes are normalized using the image height and width (no depth / 3D information needed, see Equation 10 in our [paper](https://arxiv.org/pdf/2103.01468.pdf)). Specifically, if x, y, w, h denote the two image coordinates of the bounding box center, width, and height, and W, H denote image width and height, a normalized bounding box is [x/W, y/H, w/W, h/H] (e.g., [320/640, 240/480, 100/640, 80/480] for your bounding box 0).

The camera poses are normalized differently depending on which method you are implementing. If you are unsure, I recommend predicting depth relative to the overall camera movement (see Equations 11 and 14 in our [paper](https://arxiv.org/pdf/2103.01468.pdf)). 

Notably, for ODMD, we assume that the camera pose inputs consist of three-dimensional translations (i.e., a change in x, y, and / or z position). However, the examples you provided have four dimensions. What do each of these dimensions represent?

Thanks again,
Brent

**Comment by Frank-Michel** [comment]
Thanks for the information. Using the image dimensions to normalize the bounding box is what I have thought, I was a bit confused by the formulation in the paper.
For the camera poses, I was writing them down as homogeneous transformation matrices, so the three translation vectors (camera positions) would be [[0.0, 0.0, 0.0], [0.0, 0.0, 0.2], [0.0, 0.0, 0.5]]

Frank

**Comment by griffbr** [comment]
Hi Frank,

I understand your camera poses now, thanks for clarifying. In that case, the three poses using the normalized / relative distance formulation from Equation 11 are:

Pose 0 [0, 0, 0]
Pose 1 ([0,0,0.2] - [0,0,0])  / L2 norm([0,0,0.5] - [0,0,0]) = [0,0,0.2] / 0.5 = [0, 0, 0.4]
Pose 2 ([0,0,0.5] - [0,0,0.2]) / 0.5 = [0, 0, 0.6]

I hope this example helps clarify the camera pose input. Let me know if you have any other questions!

Best,
Brent

**Comment by Frank-Michel** [comment]
Hi Brent,

That helps, thanks a lot.

Best,
Frank
