### ISSUE TITLE
Hello Sir, This Paper is Wonderful, But Sir When I have to Check My Own Test Video(  I Followed all the Process that you've told in the Previous Issues like Segment the Videos (break into image) and Feed the Image in the Sequence Order) But Sir I Don't Know Where to Feed the Sequence of the Images, Can You Please Explain How to do that Part sir, Please

### ISSUE THREAD

**Issue by Kesavan-Raman** [griffbr/ODMD#5]

**Comment by griffbr** [comment]
Hello Kesavan-Raman,

Thanks for your question. 

Have you run object detection for your sequence of images? If not, I suggest using Detectron2, which can be found here: [https://github.com/facebookresearch/detectron2](https://github.com/facebookresearch/detectron2)

Also, do you have camera motion for your video? E.g., from robot kinematics or vehicle odometry. Here is a link with more discussion on how to format camera motion: [https://github.com/griffbr/ODMD/issues/4](https://github.com/griffbr/ODMD/issues/4)

Let me know if this helps!

Best,
Brent

**Comment by Kesavan-Raman** [comment]
Hello Griffbr,

Sir, I Read this #4, Here you've explained how to estimate the Poses, But Sir in the Test Set there is only Normalized Sets, But Sir , I am having only the Segmented Video in a Sequence of Image, So Sir, How Can I Normalize My Sequence of Images Sir,

Sir and also I am a College Student and New to this Field, So Please Don't mistaken me, if I asked anything wrong,

Thanks,
Kesavan R,

**Comment by griffbr** [comment]
Hello Kesavan,

If I am understanding the situation, you only have a video sequence without any camera motion data, is that correct?

Best,
Brent

**Comment by Kesavan-Raman** [comment]
Yes Sir, Exactly I Have Only a video sequence without any camera motion data, Yes Sir Because You Said that you've taken in Mobile Phones Sir, That's why I am Trying this Sir

**Comment by griffbr** [comment]
I understand. For our mobile phone experiments, we estimated the movement between images using marking on the ground (e.g., sidewalk sections, see Section 4.1 or our [paper](https://openaccess.thecvf.com/content/CVPR2021/html/Griffin_Depth_From_Camera_Motion_and_Object_Detection_CVPR_2021_paper.html)).

 Unfortunately, our method will not work without _any_ camera motion estimate.
