### ISSUE TITLE
Inference part

### ISSUE THREAD

**Issue by GaganTC** [griffbr/ODMD#6]
Suppose if I am getting bounding box of object from yolov5 then how can we feed those bounding boxes to this model, or how can we integrate this to Yolov5.

**Comment by griffbr** [comment]
Hello GaganTC,

Thank you for your question.

To use bounding boxes from yolov5 (or any detection model) format your inputs to match the convention used at Line 48 in [/demo/demo_DBox_eval.py](https://github.com/griffbr/ODMD/blob/main/demo/demo_DBox_eval.py). 
`inputs = bb2net.inputs.to(device)`

Alternatively, you can format your inputs to match bb_3D, bb at line 43 and let bb2net do the rest (lines 46-48).
`bb_3D, bb = bb_data["bb_3D"], bb_data["bb"]`

Inference using our trained model is on Line 49.
`predictions = net(inputs).cpu().numpy()`

Inference using our closed-form solution is at Line 31 in [/demo/demo_dataset_eval.py](https://github.com/griffbr/ODMD/blob/main/demo/demo_dataset_eval.py).
`predictions = odmd.closed_form.Box_LS(bboxes, camera_movements)`

For additional reference, I would review previous discussion on data format in https://github.com/griffbr/ODMD/issues/4.

Best,
Brent

**Comment by GaganTC** [comment]
Yes I got your point, thanks for your solution, and how did you predict camera position for a particular bounding box

**Comment by griffbr** [comment]
Hi GaganTC,

Depending on the validation / test set, we estimate the relative changes in camera position using robot kinematics, vehicle odometer (z-axis only), or ground markings.

I highly recommend watching our [video presentation](https://youtu.be/38Qqh6yYdVY) or reviewing our [paper](https://openaccess.thecvf.com/content/CVPR2021/html/Griffin_Depth_From_Camera_Motion_and_Object_Detection_CVPR_2021_paper.html) for complete details.

Best,
Brent
