### ISSUE TITLE
Training Samples

### ISSUE THREAD

**Issue by Kesavan-Raman** [griffbr/ODMD#7]
Hello sir,
This is Kesavan, Sir Can you Provide the Training or Testing Image Samples with the Motion data, If you Provide that would be a great help to understand this ODMD Model more Deeply.

Thanking you,
Kesavan

**Comment by griffbr** [comment]
Hello Kesavan,

As discussed in our video presentation ([3:22](https://youtu.be/38Qqh6yYdVY?t=202)) and paper ([Section 3.3](https://openaccess.thecvf.com/content/CVPR2021/papers/Griffin_Depth_From_Camera_Motion_and_Object_Detection_CVPR_2021_paper.pdf)), our training data are simulated and generated as the network is trained. Thus, there are no real images associated with the Training Samples.

If you want to visualize the bounding boxes, you can simply draw rectangles on a blank image. Here is a [tutorial](https://www.pyimagesearch.com/2021/01/27/drawing-with-opencv/) that explains how to do this using cv2.rectangle.

Best,
Brent
