### ISSUE TITLE
How should I test the model?

### ISSUE THREAD

**Issue by farhanrw** [griffbr/ODMD#8]
Hello, after running training and evaluation as instructed, how should I now test this on my own image and video samples or live feed from webcam?

**Comment by griffbr** [comment]
Hello farhanrw,

Thanks for your question, I'm happy to help.

Please see this discussion (https://github.com/griffbr/ODMD/issues/2) on processing image/video. You will also need to use an object detector to create bounding boxes ([detectron2](https://github.com/facebookresearch/detectron2) is great for this).

Also, how are you getting camera motion data? (https://github.com/griffbr/ODMD/issues/5 for reference)

Best,
Brent
